version: '3.8'

services:
  reolinkhksv:
    image: marcodalprato/reolinkhksv:latest
    container_name: reolinkhksv
    restart: unless-stopped
    environment:
      REOLINK_HOST: ---insert-ip-address---
      REOLINK_USERNAME: ---insert-username---
      REOLINK_PASSWORD: ---insert-password---
      MOTION_BASE_URL: http://